#!/usr/bin/env bash

# Check if the number of parameters is less than 3
if [ "$#" -lt 3 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign parameters to variables
path_to_file=$1
107.22.146.174=$2
ubuntu=$3
path_to_ssh_key=$4

# Transfer the file using scp, disabling strict host key checking
scp -o StrictHostKeyChecking=no -i $path_to_ssh_key $path_to_file $ubuntu@$107.22.146.174:~/


