#!/usr/bin/env bash
#clock

hour=0
minute=1
counter=1

while [ $hour -lt 13 ]
do
  echo "Hour: $hour"

  while [ $minute -lt 60 ]
  do
    echo $minute

    ((counter++))
    ((minute++))

    if [ $counter -eq 71 ]
    then
      exit 0
    fi
  done

  ((hour++))
  minute=0
done
